import C1 from '../../assets/svg/c1.js'
import C2 from '../../assets/svg/c2.js'
import L1 from '../../assets/svg/l1.js'
import L2 from '../../assets/svg/l2.js'
import R1 from '../../assets/svg/r1.js'
import R2 from '../../assets/svg/r2.js'
import LW1 from '../../assets/svg/lw1.js'
import LW2 from '../../assets/svg/lw2.js'
import RW1 from '../../assets/svg/rw1.js'
import RW2 from '../../assets/svg/rw2.js'
import Puck from '../../assets/svg/puck.js'

const allplayers = [
  {
    id: 0,
    name: 'l1',
    Player: L1,
    src: null,
    selected: false,
    isDraggingBy: '',
    initX: 170,
    x: 170,
    corX: 0,
    initY: 103,
    y: 103,
    corY: 0,
    img: null,
  },
  {
    id: 1,
    name: 'r1',
    Player: R1,
    src: null,
    selected: false,
    isDraggingBy: '',
    initX: 170,
    x: 170,
    corX: 0,
    initY: 250,
    y: 250,
    corY: 0,
    img: null,
  },
  {
    id: 2,
    name: 'c1',
    Player: C1,
    src: null,
    selected: false,
    isDraggingBy: '',
    initX: 332,
    x: 332,
    corX: 0,
    initY: 159,
    y: 159,
    corY: 0,
    img: null,
  },
  {
    id: 3,
    name: 'lw1',
    Player: LW1,
    src: null,
    selected: false,
    isDraggingBy: '',
    initX: 300,
    x: 300,
    corX: 0,
    initY: 50,
    y: 50,
    corY: 0,
    img: null,
  },
  {
    id: 4,
    name: 'rw1',
    Player: RW1,
    src: null,
    selected: false,
    isDraggingBy: '',
    initX: 300,
    x: 300,
    corX: 0,
    initY: 303,
    y: 303,
    corY: 0,
    img: null,
  },
  {
    id: 5,
    name: 'puck',
    Player: Puck,
    src: null,
    selected: false,
    isDraggingBy: '',
    initX: 385,
    x: 385,
    corX: 0,
    initY: 189,
    y: 189,
    corY: 0,
    img: null,
  },
  {
    id: 6,
    name: 'lw2',
    Player: LW2,
    src: null,
    selected: false,
    isDraggingBy: '',
    initX: 440,
    x: 440,
    corX: 0,
    initY: 303,
    y: 303,
    corY: 0,
    img: null,
  },
  {
    id: 7,
    name: 'rw2',
    Player: RW2,
    src: null,
    selected: false,
    isDraggingBy: '',
    initX: 440,
    x: 440,
    corX: 0,
    initY: 50,
    y: 50,
    corY: 0,
    img: null,
  },
  {
    id: 8,
    name: 'c2',
    Player: C2,
    src: null,
    selected: false,
    isDraggingBy: '',
    initX: 407,
    x: 407,
    corX: 0,
    initY: 159,
    y: 159,
    corY: 0,
    img: null,
  },
  {
    id: 9,
    name: 'l2',
    Player: L2,
    src: null,
    selected: false,
    isDraggingBy: '',
    initX: 570,
    x: 570,
    corX: 0,
    initY: 250,
    y: 250,
    corY: 0,
    img: null,
  },
  {
    id: 10,
    name: 'r2',
    Player: R2,
    src: null,
    selected: false,
    isDraggingBy: '',
    initX: 570,
    x: 570,
    corX: 0,
    initY: 103,
    y: 103,
    corY: 0,
    img: null,
  },
]
export default allplayers
